### PR TITLE
Support `min-max-inverted` norm

### PR DESCRIPTION
**Pull request by MochiXu**
## Background Introduction:

I need to perform a hybrid search using **ranx** and [**MyScaleDB**](https://github.com/myscale/myscaledb). The principle is as follows:

- Use MyScale's `TextSearch` to obtain the `BM25` document scores (higher scores indicate higher relevance).
- Use MyScale's `VectorSearch` to obtain the query scores for text vectors (the distance between vectors is calculated using `Cosine` similarity, so lower scores indicate higher relevance).

When merging the vector search results and the `BM25` query results, I need to normalize the scores. However, I only found the `min-max` normalization function suitable for `BM25` scores. Therefore, I modified the code and added the `min-max-inverted` function to handle the normalization of vector search scores.

### CODE REVIEW

**Comment by MochiXu** [comment]
❤️ 👀 @diegoceccarelli

**Comment by AndreP-git** [comment]
I had a look with @diegoceccarelli and the main comment is that the metric has a lot of code shared with `min-max` . Couldn't you reuse the same code and add a parameter to change the way normalize results are computed? https://github.com/AmenRa/ranx/blob/master/ranx/normalization/min_max_norm.py#L29

@AmenRa what do you think?

**Comment by MochiXu** [comment]
@AndreP-git Following your advice, I have refined the code.

**Comment by diegoceccarelli** [comment]
@MochiXu thanks for contributing -  @AndreP-git  and I added some suggestions to your branch - please let us know what you think!  

https://github.com/MochiXu/ranx/pull/1/files

**Comment by MochiXu** [comment]
@diegoceccarelli Thank you so much for refining my code. Your improvements will make ranx more user-friendly.

**Comment by AmenRa** [comment]
Hi everyone, I am deeply sorry for the delay!
Thanks @MochiXu for the contribution.
Thanks @diegoceccarelli and @AndreP-git for the code review / refine.
Merging.

**Pull request merged**
